### ISSUE TITLE
Question about the method to calculate the score

### ISSUE THREAD

**Issue by yipliu** [thunlp/MultiRD#2]
Hi Zhang Lei,

Does the following [code](https://github.com/thunlp/MultiRD/blob/master/EnglishReverseDictionary/code/model.py#L118) prevent the model from predicting the token contained in the input sentence?
```python
score = score * mask2 + (-1e6)*(1-mask2)
```

**Comment by whoisleilei** [comment]
Yes. The word you are looking for that you don't know can not appear in your words.

**Comment by yipliu** [comment]
Thanks!

**Comment by yipliu** [comment]
Hi Zhang Lei,

I wonder if I could ask you a question. How do you distinguish between NLG and NLU?

**Comment by whoisleilei** [comment]
Whether a new text is generated?
